apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-deployment
spec:
  replicas: 1  # Number of replicas you want to run
  selector:
    matchLabels:
      app: phoenix
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: phoenix
        image: abhithetfpl/abhithetfpl:latest
        ports:
        - containerPort: 80  # Port your application listens on
